config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  namespace :api do
    devise_scope :user do 
      resources :sessions, only: [:create, :index]
    end
    resources :routines do 
      resources :completes, shallow: true
    end 
  end

  root "horses#index"
  get "/my_horses" => "horses#mine"
  # post "/api/sessions" => "api/sessions#create"

  resources :horses do
    resources :routines, shallow: true do 
      resources :completes, shallow: true
    end
  end

end

app/models/routine.rb
class Routine < ActiveRecord::Base
  belongs_to :horse
  has_many :completes

  morning_due_time = 11
  evening_due_time = 21

  def new
  end

  def create(params)
    # I want to have a hidden value that send along the id of horse's page that we are on.
    if params(:kind) == "morning"
      self.due = morning_due_time
    elsif params(:kind) =="evening"
      self.due = evening_due_time
    else
      render json: "That's not an option."
    end
  end


  def self.check_all
    # Iterate through completes
  end

end

app/controllers/api/routines_controller.rb
class Api::RoutinesController < ApplicationController
  skip_before_action protect_from_forgery with: :exception 
  # protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
  # before_action :authenticate_user!

  def index
    if Time.now.hour <= 12 #THIS IS LOCALTIME
      @tasks = Complete.incomplete("morning")
    elsif Time.now.hour > 12  #THIS IS LOCALTIME
      @tasks = Complete.incomplete("evening")
    else
      render json: "There are no tasks at this time."
      return
    end

    the_results = get_results(@tasks)

    render json: the_results
  end

  def get_results(tasks)
    the_results ||= []
    @tasks.each do |r|
      the_results.push({'id' => r.id,
      'horse_name' => r.horse.name,
      'horse_id' => r.horse_id,
      'description' => r.description,
      'kind' => r.kind,
      'phone_number' => r.horse.phone_number
      })
    end
    the_results
  end

private 
  def routine_params
    params.require(:routine).permit(:horse_id, :description, :kind, :created_at, :updated_at, :routine_id)
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  
  def new
    @horse = Horse.find(params[:horse_id])
  end

  def create
    @horse = Horse.find(params[:horse_id])
    @routine = @horse.routines.new(routine_params)
    if @routine.save!
      flash[:success] ="Routine saved"
      redirect_to @horse
    else
      flash[:error] = "Unable to save routine. Please try again."
      render :create
    end
  end

  def edit
    @routine = Routine.find(params[:id])
  end

  def update
    @routine = Routine.find(params[:id])
    @horse = Horse.find(@routine.horse_id)
    flash[:success] = "You have updated #{@horse.name}'s routine."
    redirect_to @horse 
  end

  def show
    @routine = Routine.find(params[:id])
  end

private 
  def routine_params
    params.require(:routine).permit(:horse_id, :description, :kind, :created_at, :updated_at, :routine_id)
  end
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/edit.html.erb
<p>
  <strong>Horse Name:</strong>
  <%= @routine.horse.name %>
</p>
<h3> Edit a routine </h3>
 
<%= form_for :routine, url: routine_path(@routine), method: :patch do |f| %>
  <p>
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </p>
    <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/routines/new.html.erb
<p>
  <strong>Horse Name:</strong>
  <%= @horse.name %>
</p>
<h3> Record a routine </h3>
 
<%= form_for :routine, url: horse_routines_path do |f| %>
  <p>
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </p>
    <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>