config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  namespace :api do
    devise_scope :user do 
      resources :sessions, only: [:create, :index]
    end
    resources :routines do 
      resources :completes, shallow: true
    end 
  end

  root "horses#index"
  get "/my_horses" => "horses#mine"
  # post "/api/sessions" => "api/sessions#create"

  resources :horses do
    resources :routines, shallow: true do 
      resources :completes, shallow: true
    end
  end

end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController

  def index
    @horses = Horse.all
  end

  def new
    @horse = Horse.new
  end

  def mine
    @horses = Horse.where(user: current_user)
  end

  def create
    @horse = current_user.horses.new(horse_params)
    if @horse.save
      flash[:success] = "Horse saved!"
      redirect_to @horse
    else
      flash[:error] ="Nope, didn't work"
      render :new
    end
  end

  def show
    @horse = Horse.find(params[:id])
  end

private
  def horse_params
    params.require(:horse).permit(:name, :registered_name, :birthday, :user_id, :breed, :color,:phone_number)
  end

end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/views/horses/edit.html.erb
<h1> <%="Edit #{@horse.registered_name}'s information" %> </h1>

<%=  form_for @horse, url: horse_path(@horse), method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
    <p>
    <%= f.label :registered_name %><br>
    <%= f.text_field :registered_name %>
  </p>
  <h4> Enter the phone number where you would like to receive text updates about your horse </h4>
  <p>
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </p>
  <p>
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %>
  </p>
  <p>
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </p>
  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>
  <p>
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :identifying_marks %><br>
    <%= f.text_area :identifying_marks %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/horses/index.html.erb
<h1> All Horses at Rocky Hill </h1>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Horse</th>
        <th>Owner</th>
        <th>Profile</th>
      </tr>
    </thead>

    <tbody>
      <% @horses.each do |horse| %>
        <tr>
          <td><%= horse[:name]%></td>
          <td><%= horse.user.email.split("@")[0].capitalize %></td>
          <td>
            <button><%= link_to "View Profile", horse %> </button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/horses/mine.html.erb
<h1> My Horses </h1>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Horse</th>
        <th>Owner</th>
        <th>Profile</th>
      </tr>
    </thead>

    <tbody>
      <% @horses.each do |horse| %>
        <tr>
          <td><%= horse[:name]%></td>
          <td><%= horse.user.email.split("@")[0].capitalize %></td>
          <td>
            <button><%= link_to "View Profile", horse %> </button>
          </td>
              </div>
            </td>
            <% end %>
          </tr>
      </tbody>
    </table>

app/views/horses/new.html.erb
<h1> Register your horse </h1>

<%= form_for :horse, url: horses_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
    <p>
    <%= f.label :registered_name %><br>
    <%= f.text_field :registered_name %>
  </p>
  <p>
    <%= f.label :birthday %><br>
    YYYY-MM-DD<br>
    <%= f.text_field :birthday %>
  </p>
  <p>
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </p>
  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>
  <p>
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :identifying_marks %><br>
    <%= f.text_area :identifying_marks %>
  </p>
  <br>
    <h4> Enter your phone number <br>to recieve 
    updates about your horse:</h4>
  <p>
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/horses/show.html.erb
<p>

  <h1><%= @horse.name %></h1>
</p>
 
<p>
  <strong>Registered Name:</strong><br>
  <%= @horse.registered_name %>
</p>

<p>
  <strong> Breed: </strong><br>
  <%= @horse.breed %>
</p>

<p>
  <strong> Color: </strong><br>
  <%= @horse.color %>
</p><br><br>

<p>
  <h3> <%= @horse.name %>'s Daily Routine</h3><br>
  <% if @horse.routines.count > 1 %>
  <% @horse.routines.last(2).each do |routine| %>
  <br><strong><%= routine.kind %></strong><br>
  <%= routine.description %><br>
  <%= link_to "Update", edit_routine_path(routine) %>
  <% end %>
  <% else %>
  <strong><%= link_to "Record Care information for #{@horse.name}", new_horse_routine_path(horse_id: @horse.id) %></strong>
  <% end %>
</p>