config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  namespace :api do
    devise_scope :user do 
      resources :sessions, only: [:create, :index]
    end
    resources :routines do 
      resources :completes, shallow: true
    end 
  end

  root "horses#index"
  get "/my_horses" => "horses#mine"
  # post "/api/sessions" => "api/sessions#create"

  resources :horses do
    resources :routines, shallow: true do 
      resources :completes, shallow: true
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OurBarnBoard</title>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link href='//fonts.googleapis.com/css?family=Roboto:100,400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>

<body>
<nav id="icononav">
  <a href="/horses" class="user">
    <img class="delay" src="http://freeiconbox.com/icon/256/33093.png" alt="OurBarnBoard">"Our Barn Board"</a>
  </a>
  <ul class="links">
    <li><strong><%= link_to "Home", root_path %></strong></li>
    <li><strong><%= link_to "My Horses", my_horses_path %></strong></li>
    <li><strong><%= link_to "Register Horse", new_horse_path %></strong></li>



<% if user_signed_in? %>

    <strong class="navbar-link">Logged in as </strong><br><strong class="navbar-link"><%= current_user.email.split("@")[0] %></strong><br>
 
    <strong><%= link_to "Logout", destroy_user_session_path, :class =>'navbar-link', method: :delete %></strong>

<% else %>

    <br>
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

<% end %>

</ul>

</nav>


<div class="container">

<div class="flash">
       <% flash.each do |name, msg| %>
       <div class="alert alert-<%= flash_class name %>">
         <%= msg %>
       </div>
       <% end %>
     </div>

<%= yield %>

</div>

</body>
</html>